Importing the dependencies

In [1]:
import pandas as pd

Importing the data

In [2]:
train_data = pd.read_csv(r'Datasets/train.csv')
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie
0,30192,gpt-4-1106-preview,gpt-4-0613,"[""Is it morally right to try to have a certain...","[""The question of whether it is morally right ...","[""As an AI, I don't have personal beliefs or o...",1,0,0
1,53567,koala-13b,gpt-4-0613,"[""What is the difference between marriage lice...","[""A marriage license is a legal document that ...","[""A marriage license and a marriage certificat...",0,1,0
2,65089,gpt-3.5-turbo-0613,mistral-medium,"[""explain function calling. how would you call...","[""Function calling is the process of invoking ...","[""Function calling is the process of invoking ...",0,0,1
3,96401,llama-2-13b-chat,mistral-7b-instruct,"[""How can I create a test set for a very rare ...","[""Creating a test set for a very rare category...","[""When building a classifier for a very rare c...",1,0,0
4,198779,koala-13b,gpt-3.5-turbo-0314,"[""What is the best way to travel from Tel-Aviv...","[""The best way to travel from Tel Aviv to Jeru...","[""The best way to travel from Tel-Aviv to Jeru...",0,1,0

In [3]:
test_data = pd.read_csv(r'Datasets/test.csv')
test_data

,id,prompt,response_a,response_b
0,136060,"[""I have three oranges today, I ate an orange ...","[""You have two oranges today.""]","[""You still have three oranges. Eating an oran..."
1,211333,"[""You are a mediator in a heated political deb...","[""Thank you for sharing the details of the sit...","[""Mr Reddy and Ms Blue both have valid points ..."
2,1233961,"[""How to initialize the classification head wh...","[""When you want to initialize the classificati...","[""To initialize the classification head when p..."

In [4]:
import re
def text_cleaning(text):
    text = text.lower()
    text = text.replace("\\/", "/").replace("\\n", " ").replace("\t", " ")
    text = re.sub(r"[^a-zA-Z0-9\s.,!?()]+", "", text) 
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

train_data['prompt'] = train_data['prompt'].apply(text_cleaning)
train_data['response_a'] = train_data['response_a'].apply(text_cleaning)
train_data['response_b'] = train_data['response_b'].apply(text_cleaning)
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie
0,30192,gpt-4-1106-preview,gpt-4-0613,is it morally right to try to have a certain p...,the question of whether it is morally right to...,"as an ai, i dont have personal beliefs or opin...",1,0,0
1,53567,koala-13b,gpt-4-0613,what is the difference between marriage licens...,a marriage license is a legal document that al...,a marriage license and a marriage certificate ...,0,1,0
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling. how would you call a...,function calling is the process of invoking or...,function calling is the process of invoking a ...,0,0,1
3,96401,llama-2-13b-chat,mistral-7b-instruct,how can i create a test set for a very rare ca...,creating a test set for a very rare category c...,when building a classifier for a very rare cat...,1,0,0
4,198779,koala-13b,gpt-3.5-turbo-0314,what is the best way to travel from telaviv to...,the best way to travel from tel aviv to jerusa...,the best way to travel from telaviv to jerusal...,0,1,0

In [5]:
test_data['prompt'] = test_data['prompt'].apply(text_cleaning)
test_data['response_a'] = test_data['response_a'].apply(text_cleaning)
test_data['response_b'] = test_data['response_b'].apply(text_cleaning)
test_data.head()

,id,prompt,response_a,response_b
0,136060,"i have three oranges today, i ate an orange ye...",you have two oranges today.,you still have three oranges. eating an orange...
1,211333,you are a mediator in a heated political debat...,thank you for sharing the details of the situa...,mr reddy and ms blue both have valid points in...
2,1233961,how to initialize the classification head when...,when you want to initialize the classification...,to initialize the classification head when per...

In [6]:
train_data[['winner_model_a', 'winner_model_b', 'winner_tie']].sum()

winner_model_a    20064
winner_model_b    19652
winner_tie        17761
dtype: int64

In [7]:
train_data[['model_a', 'model_b']].nunique()

model_a    64
model_b    64
dtype: int64

In [8]:
train_data['response_a_len'] = train_data['response_a'].apply(lambda x: len(x))
train_data['response_b_len'] = train_data['response_b'].apply(lambda x: len(x))

In [9]:
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,response_a_len,response_b_len
0,30192,gpt-4-1106-preview,gpt-4-0613,is it morally right to try to have a certain p...,the question of whether it is morally right to...,"as an ai, i dont have personal beliefs or opin...",1,0,0,4373,1193
1,53567,koala-13b,gpt-4-0613,what is the difference between marriage licens...,a marriage license is a legal document that al...,a marriage license and a marriage certificate ...,0,1,0,3073,3529
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling. how would you call a...,function calling is the process of invoking or...,function calling is the process of invoking a ...,0,0,1,837,1683
3,96401,llama-2-13b-chat,mistral-7b-instruct,how can i create a test set for a very rare ca...,creating a test set for a very rare category c...,when building a classifier for a very rare cat...,1,0,0,3144,1540
4,198779,koala-13b,gpt-3.5-turbo-0314,what is the best way to travel from telaviv to...,the best way to travel from tel aviv to jerusa...,the best way to travel from telaviv to jerusal...,0,1,0,1268,749

In [10]:
test_data['response_a_len'] = test_data['response_a'].apply(lambda x: len(x))
test_data['response_b_len'] = test_data['response_b'].apply(lambda x: len(x))

In [11]:
test_data.head()

,id,prompt,response_a,response_b,response_a_len,response_b_len
0,136060,"i have three oranges today, i ate an orange ye...",you have two oranges today.,you still have three oranges. eating an orange...,27,110
1,211333,you are a mediator in a heated political debat...,thank you for sharing the details of the situa...,mr reddy and ms blue both have valid points in...,1437,454
2,1233961,how to initialize the classification head when...,when you want to initialize the classification...,to initialize the classification head when per...,3899,3497

In [12]:
train_data['response_a_un'] = train_data['response_a'].apply(lambda x: len(set(x.split(" "))))
train_data['response_b_un'] = train_data['response_b'].apply(lambda x: len(set(x.split(" "))))
train_data['prompt_un'] = train_data['prompt'].apply(lambda x: len(set(x.split(" "))))

In [14]:
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,response_a_len,response_b_len,response_a_un,response_b_un,prompt_un
0,30192,gpt-4-1106-preview,gpt-4-0613,is it morally right to try to have a certain p...,the question of whether it is morally right to...,"as an ai, i dont have personal beliefs or opin...",1,0,0,4373,1193,374,131,25
1,53567,koala-13b,gpt-4-0613,what is the difference between marriage licens...,a marriage license is a legal document that al...,a marriage license and a marriage certificate ...,0,1,0,3073,3529,148,248,30
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling. how would you call a...,function calling is the process of invoking or...,function calling is the process of invoking a ...,0,0,1,837,1683,81,122,9
3,96401,llama-2-13b-chat,mistral-7b-instruct,how can i create a test set for a very rare ca...,creating a test set for a very rare category c...,when building a classifier for a very rare cat...,1,0,0,3144,1540,167,116,15
4,198779,koala-13b,gpt-3.5-turbo-0314,what is the best way to travel from telaviv to...,the best way to travel from tel aviv to jerusa...,the best way to travel from telaviv to jerusal...,0,1,0,1268,749,121,77,13

In [15]:
test_data['response_a_un'] = test_data['response_a'].apply(lambda x: len(set(x.split(" "))))
test_data['response_b_un'] = test_data['response_b'].apply(lambda x: len(set(x.split(" "))))
test_data['prompt_un'] = test_data['prompt'].apply(lambda x: len(set(x.split(" "))))

In [16]:
test_data.head()

,id,prompt,response_a,response_b,response_a_len,response_b_len,response_a_un,response_b_un,prompt_un
0,136060,"i have three oranges today, i ate an orange ye...",you have two oranges today.,you still have three oranges. eating an orange...,27,110,5,17,13
1,211333,you are a mediator in a heated political debat...,thank you for sharing the details of the situa...,mr reddy and ms blue both have valid points in...,1437,454,125,51,68
2,1233961,how to initialize the classification head when...,when you want to initialize the classification...,to initialize the classification head when per...,3899,3497,176,189,28

In [17]:
def combine_p_r(row): 
    return (
        f"{row['prompt']}: {row['response_a']}",
        f"{row['prompt']}: {row['response_b']}"
    )

In [18]:
train_data[['combined_a', 'combined_b']] = train_data.apply(combine_p_r, axis=1, result_type='expand')
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,response_a_len,response_b_len,response_a_un,response_b_un,prompt_un,combined_a,combined_b
0,30192,gpt-4-1106-preview,gpt-4-0613,is it morally right to try to have a certain p...,the question of whether it is morally right to...,"as an ai, i dont have personal beliefs or opin...",1,0,0,4373,1193,374,131,25,is it morally right to try to have a certain p...,is it morally right to try to have a certain p...
1,53567,koala-13b,gpt-4-0613,what is the difference between marriage licens...,a marriage license is a legal document that al...,a marriage license and a marriage certificate ...,0,1,0,3073,3529,148,248,30,what is the difference between marriage licens...,what is the difference between marriage licens...
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling. how would you call a...,function calling is the process of invoking or...,function calling is the process of invoking a ...,0,0,1,837,1683,81,122,9,explain function calling. how would you call a...,explain function calling. how would you call a...
3,96401,llama-2-13b-chat,mistral-7b-instruct,how can i create a test set for a very rare ca...,creating a test set for a very rare category c...,when building a classifier for a very rare cat...,1,0,0,3144,1540,167,116,15,how can i create a test set for a very rare ca...,how can i create a test set for a very rare ca...
4,198779,koala-13b,gpt-3.5-turbo-0314,what is the best way to travel from telaviv to...,the best way to travel from tel aviv to jerusa...,the best way to travel from telaviv to jerusal...,0,1,0,1268,749,121,77,13,what is the best way to travel from telaviv to...,what is the best way to travel from telaviv to...

In [19]:
test_data[['combined_a', 'combined_b']] = test_data.apply(combine_p_r, axis=1, result_type='expand')
test_data.head()

,id,prompt,response_a,response_b,response_a_len,response_b_len,response_a_un,response_b_un,prompt_un,combined_a,combined_b
0,136060,"i have three oranges today, i ate an orange ye...",you have two oranges today.,you still have three oranges. eating an orange...,27,110,5,17,13,"i have three oranges today, i ate an orange ye...","i have three oranges today, i ate an orange ye..."
1,211333,you are a mediator in a heated political debat...,thank you for sharing the details of the situa...,mr reddy and ms blue both have valid points in...,1437,454,125,51,68,you are a mediator in a heated political debat...,you are a mediator in a heated political debat...
2,1233961,how to initialize the classification head when...,when you want to initialize the classification...,to initialize the classification head when per...,3899,3497,176,189,28,how to initialize the classification head when...,how to initialize the classification head when...

In [20]:
train_data['winner'] = pd.from_dummies(train_data[['winner_model_a', 'winner_model_b', 'winner_tie']])
train_data['winner'] = train_data['winner'].map({'winner_model_a':0, 'winner_model_b':1, 'winner_tie':2})
train_data.drop(['winner_model_a', 'winner_model_b', 'winner_tie'], axis=1, inplace=True)
train_data.head()

,id,model_a,model_b,prompt,response_a,response_b,response_a_len,response_b_len,response_a_un,response_b_un,prompt_un,combined_a,combined_b,winner
0,30192,gpt-4-1106-preview,gpt-4-0613,is it morally right to try to have a certain p...,the question of whether it is morally right to...,"as an ai, i dont have personal beliefs or opin...",4373,1193,374,131,25,is it morally right to try to have a certain p...,is it morally right to try to have a certain p...,0
1,53567,koala-13b,gpt-4-0613,what is the difference between marriage licens...,a marriage license is a legal document that al...,a marriage license and a marriage certificate ...,3073,3529,148,248,30,what is the difference between marriage licens...,what is the difference between marriage licens...,1
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling. how would you call a...,function calling is the process of invoking or...,function calling is the process of invoking a ...,837,1683,81,122,9,explain function calling. how would you call a...,explain function calling. how would you call a...,2
3,96401,llama-2-13b-chat,mistral-7b-instruct,how can i create a test set for a very rare ca...,creating a test set for a very rare category c...,when building a classifier for a very rare cat...,3144,1540,167,116,15,how can i create a test set for a very rare ca...,how can i create a test set for a very rare ca...,0
4,198779,koala-13b,gpt-3.5-turbo-0314,what is the best way to travel from telaviv to...,the best way to travel from tel aviv to jerusa...,the best way to travel from telaviv to jerusal...,1268,749,121,77,13,what is the best way to travel from telaviv to...,what is the best way to travel from telaviv to...,1

In [24]:
X = train_data[["prompt", "response_a", "response_b", "response_a_len", "response_b_len", "response_a_un", "response_b_un", 
              "prompt_un", "combined_a", "combined_b"]]
Y = train_data[['winner']]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
from sklearn.metrics import accuracy_score

In [22]:
numeric_features = [
    'response_a_len', 'response_b_len', 'response_a_un', 'response_b_un', 'prompt_un'
]

text_features = [
    'prompt', 'response_a', 'response_b', 'combined_a', 'combined_b'
]

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [27]:
# TF-IDF Vectorization
tfidf_prompt = TfidfVectorizer(max_features=1500, stop_words='english')
tfidf_responses = TfidfVectorizer(max_features=1500, stop_words='english')

prompt_tf = tfidf_prompt.fit_transform(X_train['prompt'])
response_a_tf = tfidf_responses.fit_transform(X_train['response_a'])
response_b_tf = tfidf_responses.fit_transform(X_train['response_b'])
combined_a_tf = tfidf_responses.fit_transform(X_train['combined_a'])
combined_b_tf = tfidf_responses.fit_transform(X_train['combined_b'])

# Scaling numeric features
scaler = StandardScaler()
X_train_numeric = scaler.fit_transform(X_train[numeric_features])
X_test_numeric = scaler.transform(X_test[numeric_features])

# Combine TF-IDF and scaled numeric features
X_train_tf = hstack([
    prompt_tf, 
    response_a_tf, 
    response_b_tf, 
    combined_a_tf, 
    combined_b_tf, 
    X_train_numeric
])

# Do the same for test set
prompt_tf_test = tfidf_prompt.transform(X_test['prompt'])
response_a_tf_test = tfidf_responses.transform(X_test['response_a'])
response_b_tf_test = tfidf_responses.transform(X_test['response_b'])
combined_a_tf_test = tfidf_responses.transform(X_test['combined_a'])
combined_b_tf_test = tfidf_responses.transform(X_test['combined_b'])

X_test_tf = hstack([
    prompt_tf_test, 
    response_a_tf_test, 
    response_b_tf_test, 
    combined_a_tf_test, 
    combined_b_tf_test, 
    X_test_numeric
])

In [31]:
from xgboost import XGBClassifier

In [32]:
xgb_model = XGBClassifier(n_estimators=500, subsample=0.8, min_child_weight=10, max_depth=3, learning_rate=0.1, gamma=0, colsample_bytree=0.8)
xgb_model.fit(X_train_tf, Y_train)
Y_pred = xgb_model.predict(X_test_tf)
print(f"Accuracy: {accuracy_score(Y_test, Y_pred)}")

Accuracy: 0.46242171189979125

In [33]:
# TF-IDF Vectorization
# tfidf_prompt = TfidfVectorizer(max_features=1500, stop_words='english')
# tfidf_responses = TfidfVectorizer(max_features=1500, stop_words='english')

prompt_tf = tfidf_prompt.transform(test_data['prompt'])
response_a_tf = tfidf_responses.transform(test_data['response_a'])
response_b_tf = tfidf_responses.transform(test_data['response_b'])
combined_a_tf = tfidf_responses.transform(test_data['combined_a'])
combined_b_tf = tfidf_responses.transform(test_data['combined_b'])

# Scaling numeric features
#scaler = StandardScaler()
test_numeric = scaler.transform(test_data[numeric_features])

# Combine TF-IDF and scaled numeric features
X_test_tf = hstack([
    prompt_tf, 
    response_a_tf, 
    response_b_tf, 
    combined_a_tf, 
    combined_b_tf, 
    test_numeric
])

In [34]:
prediction = xgb_model.predict_proba(X_test_tf)
df_sample = pd.DataFrame(data=prediction, columns=['winner_model_a', 'winner_model_b', 'winner_tie'])

In [ ]:
submission = pd.concat([test_data[['id']], df_sample], axis=1)
submission.to_csv('Datasetes/submission.csv', index=False)
submission

        id  winner_model_a  winner_model_b  winner_tie
0   136060        0.268963        0.291943    0.439094
1   211333        0.520529        0.215500    0.263970
2  1233961        0.362751        0.373992    0.263257